#spring.application.name=customer
server.port=8081


spring.application.name=businessdomain-customer

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.healthcheck.enabled=true
eureka.client.fetch-registry=true
spring.cloud.config.override-none=false


management.endpoints.web.exposure.include=*
management.endpoint.info.enabled=true
management.endpoint.health.enabled=true


management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

#server.servlet.context-path=/business/v2

#spring.security.user.name=admin
#spring.security.user.password=qwerty
#spring.security.user.roles="ADMIN"

#Integra el estado del circuito con Spring Boot Actuator.
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true

#Resilience4j mirará el resultado de las últimas 10 llamadas para decidir si debe abrir o cerrar el circuito.
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
#Establece el número mínimo de llamadas necesarias para empezar a calcular errores.
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
#Define cuántas llamadas de "prueba" se permiten cuando el circuito está en estado Medio Abierto.
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
#Activa el paso automático del estado Abierto al Medio Abierto
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
#Es el tiempo que el circuito se queda "abierto" (bloqueando todo el tráfico).
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
#Es el umbral de error en porcentaje.
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
#Define el tamaño del buffer interno para los eventos del circuito (como cambios de estado).
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10

